### PR TITLE
Test based on pre-release deps

### PR DESCRIPTION
**Pull request by lpsinger**
Note: merge #171 first.

### CODE REVIEW

**Comment by lpsinger** [comment]
Fixed by #175, right, @pllim?

**Comment by pllim** [comment]
Ops, I didn't see this one. What was the purpose of this PR?

**Comment by pllim** [comment]
Oh, I see. I didn't add any "predeps" in #175. Though you might be better off opening a new PR rather than try to rebase this. Sorry for the conflicts!

**Review by pllim — APPROVED** [review]
Seems straightforward enough. Thanks!

**Pull request merged**
