### PR TITLE
Use 'long double' for x,y,z arguments

### PR DESCRIPTION
**Pull request by dstndstn**
- use cosl,sinl for radec_to_healpixlf
- compute 1-vz in long double

### CODE REVIEW

**Comment by cdeil** [comment]
There's a bit of a concern with this, in the sense that it probably won't fix the issue for all users: some will end up with only "double" precision still (see https://en.wikipedia.org/wiki/Long_double).

Even worse would be if there's a distribution problem where binaries (e.g. Windows from conda-forge) don't work at all for some users (e.g. some Windows machines); I don't know if that's a real concern.

I would suggest we merge tomorrow, and continue with more edits and checks in the next days.

Unless there is a more stable way to do that computation using only `double`.
@mreinicke - do you know if there is a trick to get this numerically stable?

**Comment by dstndstn** [comment]
In this case it's the sin(Dec) that drops precision; Dec->90 degrees so sin(Dec)->1

**Comment by mreineck** [comment]
Yes, that's why I think it should be safer to use cos(Dec) (i.e. `sqrt(x*x + y*y)`) instead of sin(Dec) (i.e. z) in this situation.

I see similar code in other places in the package... the `z2dec` function in starutil.inc for example will fail badly near the poles. I'd recommend something like

```
double xyz2dec(double x, double y, double z)
  {
  return M_PI/2 - atan2(sqrt(x*x+y*y), z);
  }
```
It's not much slower, and it works extremely reliably.

**Comment by dstndstn** [comment]
I tried this in #94 - thanks for the tip! - seems to work in our one polar test case

**Comment by cdeil** [comment]
@mreineck @dstndstn - Thank you!
Merging #94 now and closing this one without merging.

**Pull request closed without merging**
