### PR TITLE
Add HEALPix.from_header

### LINKED ISSUE #126: Add factory method to construct a HEALPix object from a FITS header
As described by @astrofrog in #98, add a `HEALPix.from_header` factory method to create a HEALPix object from a FITS header. What about moving the FITS metadata helper functions from `reproject.healpix.utils` to this package?

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #126.

### CODE REVIEW

**Comment by cdeil** [comment]
@astrofrog - thoughts?

**Comment by lpsinger** [comment]
The test failures look like they are unrelated.

**Comment by lpsinger** [comment]
I would like to add astropy-healpix example code to the [LIGO/Virgo Public Alerts User Guide](https://emfollow.docs.ligo.org/userguide/). Any chance of getting this reviewed?

**Comment by cdeil** [comment]
CI fails look unrelated.

**Comment by cdeil** [comment]
> I would like to add astropy-healpix example code to the LIGO/Virgo Public Alerts User Guide. Any chance of getting this reviewed?

From a very quick look, this looks very cool. When should it be reviewed?

Maybe you could open a new issue or send an email, since it's unrelated to this PR, no?

**Pull request merged**
