### PR TITLE
Unpin hypothesis

### LINKED ISSUE #160: Unpin hypothesis
We should unpin hypothesis:

https://github.com/astropy/astropy-healpix/blob/1bb6875a3c435d6d15118357ad6a551e66d0247a/setup.cfg#L26

as it now conflicts with the pytest-astropy minimum requirement.

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #160.

### CODE REVIEW

**Comment by pllim** [comment]
Hard to know if this works or not when the CI won't run on PR. Can we make sure this CI is run as part of the PR first?

**Comment by lpsinger** [comment]
Of course, I forgot that the CI was busted.

**Comment by lpsinger** [comment]
Blocked by #171.

**Comment by lpsinger** [comment]
@pllim, please review.

**Review by pllim — APPROVED** [review]
Tests passed, so LGTM. Thanks!

**Pull request merged**
