### PR TITLE
MNT: Replace master with main

### PR DESCRIPTION
**Pull request by pllim**
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.

This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

This is part of #149

### CODE REVIEW

**Comment by lpsinger** [comment]
Looks like this is failing due to pytest-cov dependencies and needs to be rebased.

**Comment by pllim** [comment]
Rebased. 🤞

**Comment by lpsinger** [comment]
I wonder if Readthedocs is smart enough to adjust when we rename the primary branch...

**Review by lpsinger — APPROVED** [review]

**Comment by pllim** [comment]
> if Readthedocs is smart enough

Good question! See readthedocs/readthedocs.org#7907

**Comment by lpsinger** [comment]
@astrofrog, looks like you, or someone else who controls the Astropy packages on readthedocs, will need to update that manually.

**Comment by pllim** [comment]
https://readthedocs.org/projects/astropy-healpix/ says the following people have admin access on the RTD side -- `astropy`, @cdeil , @astrofrog , @lpsinger

**Comment by lpsinger** [comment]
Yes, @astrofrog granted me access and I fixed it.

**Pull request merged**
