### PR TITLE
Update oldest tested version of Astropy to 4

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Still a little old but since CI is green, sure. Thanks!

**Comment by pllim** [comment]
Does this need a change log?

**Comment by lpsinger** [comment]
> Does this need a change log?

It does. I just added one to the PR.

**Comment by lpsinger** [comment]
> Still a little old but since CI is green, sure. Thanks!

I agree, but I'm happy to keep supporting it up until the tests break.

**Pull request merged**
