### PR TITLE
Fix bilinear interpolation

### PR DESCRIPTION
**Pull request by astrofrog**
This fixes both #54 (dealing properly with all corner cases) and #55 (added a function to get the interpolation weights) and also allows the interpolated array to be N-dimensional.

Things that still need to be done:

* [x] Better document the new C code
* [x] Fix healpy compat tests (results are mostly fine but there are precision issues in places)
* [x] Add some tests of the Python core functions

Other than that this is almost ready to go!

### CODE REVIEW

**Comment by astrofrog** [comment]
@cdeil - are you interested in reviewing this or shall I just merge?

The interpolation and interpolation weights are now checked against healpy - I discovered that the way I was interpolating was quite different to healpy (and had issues e.g. #54) but now the two agree. The reason for writing the interpolation in C instead of Cython is because this routine is closely coupled with a number of other C functions from astrometry.net, so it was much cleaner to do it this way (and the C code is very simple anyway).

**Comment by astrofrog** [comment]
Btw there are apparently still a few rare corner cases where healpy and this package disagree for the weights, but I think these are literal corner cases where a point is on a boundary between two pixels. Investigating.

**Comment by astrofrog** [comment]
Since this fixes precision issues in the C healpix code, it may well have solved https://github.com/astropy/astropy-healpix/issues/39 - I added the examples from there here as known examples and they are passing.

**Comment by cdeil** [comment]
I only reviewed the diff for 5 min. Tests and docstrings seem OK, I don't have the expertise / time to review the algorithm.  👍  to merge.

Just one comment: in `healpixl_compose_ring` the expressions are sprinkled with a lot of `(int64_t)` to cast ints to 64 bit. I think it would be easier to just take `int64_t` as input and avoid any int typecasting inside the functions.

Thanks!

**Comment by astrofrog** [comment]
> Just one comment: in healpixl_compose_ring the expressions are sprinkled with a lot of (int64_t) to cast ints to 64 bit. I think it would be easier to just take int64_t as input and avoid any int typecasting inside the functions.

I agree, I'm planning another PR to just convert all the ints to int64_t to make this cleaner

**Pull request merged**
